" Generated by vim-plug
" Tue Oct  7 17:15:46 2025
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['bufexplorer'].commit = 'b96d275811b92e86ee52be3112e1de735ba08fb9'
silent! let g:plugs['cmp-buffer'].commit = 'b74fab3656eea9de20a9b8116afa3cfc4ec09657'
silent! let g:plugs['cmp-cmdline'].commit = 'd126061b624e0af6c3a556428712dd4d4194ec6d'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'bd5a7d6db125d4654b50eeae9f5217f24bb22fd3'
silent! let g:plugs['cmp-path'].commit = 'c642487086dbd9a93160e1679a1327be111cbc25'
silent! let g:plugs['fzf'].commit = 'b51bc6b50e90169553c48209c00c5f4d548ec0a0'
silent! let g:plugs['fzf-lua'].commit = 'a13c5c500b60f076b7ae1ae5df3cd4b547418ca1'
silent! let g:plugs['indent-blankline.nvim'].commit = '3d08501caef2329aba5121b753e903904088f7e6'
silent! let g:plugs['lspkind.nvim'].commit = '3ddd1b4edefa425fda5a9f95a4f25578727c0bb3'
silent! let g:plugs['neon'].commit = '7765aaa7d1cd3804176140644640766e4411c766'
silent! let g:plugs['nerdcommenter'].commit = '02a3b6455fa07b61b9440a78732f1e9b7876c991'
silent! let g:plugs['nightfox.nvim'].commit = 'ba47d4b4c5ec308718641ba7402c143836f35aa9'
silent! let g:plugs['nvim-cmp'].commit = 'b5311ab3ed9c846b585c0c15b7559be131ec4be9'
silent! let g:plugs['nvim-lspconfig'].commit = 'e688b486fe9291f151eae7e5c0b5a5c4ef980847'
silent! let g:plugs['nvim-treesitter'].commit = '42fc28ba918343ebfd5565147a42a26580579482'
silent! let g:plugs['nvim-web-devicons'].commit = 'b8221e42cf7287c4dcde81f232f58d7b947c210d'
silent! let g:plugs['plenary.nvim'].commit = 'b9fd5226c2f76c951fc8ed5923d85e4de065e509'
silent! let g:plugs['tailwind-tools.nvim'].commit = 'fbe982901d4508b0dcd80e07addf0fcb6dab6c49'
silent! let g:plugs['typescript-tools.nvim'].commit = 'bf11d98ad5736e1cbc1082ca9a03196d45c701f1'
silent! let g:plugs['ultisnips'].commit = 'b22a86f9dcc5257624bff3c72d8b902eac468aad'
silent! let g:plugs['vim-airline'].commit = '159573187e9996d06cf26e49a533f424f4d70b43'
silent! let g:plugs['vim-fugitive'].commit = '61b51c09b7c9ce04e821f6cf76ea4f6f903e3cf4'
silent! let g:plugs['vim-matchup'].commit = 'ca538c3bb02836510526ff7d07cf7e4c8e9a3b90'
silent! let g:plugs['vim-polyglot'].commit = 'f061eddb7cdcc614c8406847b2bfb53099832a4e'
silent! let g:plugs['vim-prettier'].commit = '7dbdbb12c50a9f4ba72390cce2846248e4368fd0'
silent! let g:plugs['vim-snippets'].commit = 'f371d635f6f6350d34bbb483e37e383db322d145'
silent! let g:plugs['vim-toggle'].commit = 'c1c0eaab76e82968d72bc03aa77974e754f6e2e8'
silent! let g:plugs['vscode.nvim'].commit = 'cb9df0873c10a21d05362455ae3bb355eadcef6b'
silent! let g:plugs['wildfire.vim'].commit = 'dfcf48aad2e80c63272df67a1b81e37cbc443412'
silent! let g:plugs['winresizer'].commit = '9bd559a03ccec98a458e60c705547119eb5350f3'
silent! let g:plugs['xoria256.vim'].commit = 'ae38fd50b365052ed4ddbc79a006a45628d5786a'

PlugUpdate!

